# Page 8 LWS
LWS_8 = ['das Broetchen',
'das Brot',
'das Ei',
'das Mehl',
'das Wuerstchen',
'der Apfel',
'der Euro',
'der Hunger',
'der Joghurt',
'der Kafee',
'der Kuchen',
'der Saft',
'der Zucker',
'die Banane',
'die Birne',
'die Butter',
'die Kartoffel',
'die Milch',
'die Orange',
'die Pfannkuchen',
'die Schokolade',
'die Tomate',
'die Welt',
'die Zwiebel']

# Page 9 LWS
LWS_9 = ['das Bier',
'das Fleisch',
'das Gemuese',
'das Gramm',
'das Hackfleisch',
'das Kilo',
'das Lebensmeittel',
'das Mineralwasser',
'das Obst',
'das Oel',
'das Pfund',
'das Regal',
'das Salz',
'das Sonderangebot',
'das Wasser',
'der Cent',
'der Fisch',
'der Kaese',
'der Liter',
'der Preis',
'der Prospeckt',
'der Reis',
'der Tee',
'der Wein',
'die Abteilung',
'die Wurst']

# Page 10-11 LWS
LWS_10_11 = ['das Cola',
'das Essen',
'das Getraenk',
'das Glas',
'das Haehnchen',
'das Restaurant',
'das Rezept',
'das Steak',
'der Durst',
'der Pfeffer',
'der Salat',
'der Tag',
'die Dose',
'die Flasche',
'die Mensa',
'die Pizza',
'die PommesFrites',
'die Portion',
'die Sahne',
'die Sosse',
'die Suppe']

LWS_12_13 = ["die Wohnung",
"die Lampe",
"das Zimmer",
"die Kueche",
"das Bad",
"der Flur",
"die Toilette",
"der Balkon",
"das Wohnzimmer",
"das Haus",
"der Monat",
"das Beispiel",
"der Schrank",
"der Kuehlschrank",
"das Sofa",
"der Tisch",
"der Stuhl",
"der Fernseher",
"die Dusche",
"der Herd",
"die Badewanne",
"der Teppich",
"der Sessel",
"die Moebel",
"das Geraet",
"die Farbe",
"der Zentimeter",
"das Handy"]

LWS_14_15 = ["die Arbeit",
"die Anzeige",
"das Ehepaar",
"der Garten",
"das Apartment",
"der Raum",
"der Stock",
"der Anruf",
"das TV",
"die Garage",
"der Quadrameter",
"die Miete",
"das Buch",
"der Stift",
"der Schreibtisch",
"das Holz",
"der Meter",
"der Platz",
"der Computer",
"das Heft"]

others = ["die Dozentin",
"die Vorlesung",
"der Name",
"das Papier",
"der Buchstabe",
"der Satz",
"das Wort",
"das Gespraech",
"das Handy",
"der Kochkurs",
"der Rotwein",
"die Traube",
"das Geld",
"die Melone",
"die Tuete",
"die Zeit",
"das Problem",
"das Buecherregal",
"das Picknick",
"der Beruf",
"der Geburtsort",
"das Heimatland",
"der Familienstand"
]